#!/bin/bash
# LIS DEMO SCRIPT - Run this for a 2-minute live demo

set -e

echo "🎓 LECTURE INTELLIGENCE SYSTEM - DEMO SCRIPT"
echo "=============================================="
echo ""
echo "This script guides you through a 2-minute demo"
echo "showing all core LIS features."
echo ""
echo "Prerequisites:"
echo "✓ npm run dev is running (http://localhost:5173)"
echo "✓ Supabase is set up with database migrated"
echo "✓ .env.local is configured"
echo ""
echo "Press Enter to start..."
read

# PART 1: AUTHENTICATION
echo ""
echo "📝 PART 1: SIGN UP (30 seconds)"
echo "=================================="
echo "1. Visit http://localhost:5173"
echo "2. Click 'Get Started'"
echo "3. Sign Up as PROFESSOR"
echo "   - Email: prof@demo.com"
echo "   - Password: Demo123456"
echo "4. Click 'Create Account'"
echo ""
echo "Press Enter when professor is signed in..."
read

# PART 2: CREATE COURSE
echo ""
echo "🏫 PART 2: CREATE COURSE (15 seconds)"
echo "======================================="
echo "1. You're now on Professor Dashboard"
echo "2. Click '+ Create Course' button"
echo "3. Enter Course Name: 'Quantum Mechanics'"
echo "4. Click 'Create Course'"
echo "5. Click the course card to select it"
echo ""
echo "Press Enter when course is selected..."
read

# PART 3: CREATE LECTURE
echo ""
echo "📚 PART 3: CREATE LECTURE (20 seconds)"
echo "========================================="
echo "1. Click '+ Create Lecture' button"
echo "2. Fill the form:"
echo "   - Title: 'Wave Functions Fundamentals'"
echo "   - Main Topic: 'Quantum Mechanics'"
echo "   - Subtopics: 'Wave Function, Schrodinger Equation, Probability Density'"
echo "3. Click 'Create Lecture'"
echo "4. Expand the lecture item"
echo "5. Click 'Select & View Feedback'"
echo ""
echo "Your right panel should show 'No feedback submitted yet'"
echo ""
echo "Press Enter when lecture is selected..."
read

# PART 4: STUDENT ACCOUNTS
echo ""
echo "👨‍🎓 PART 4: CREATE STUDENT ACCOUNTS (30 seconds)"
echo "==============================================="
echo "1. Open a NEW INCOGNITO/PRIVATE window"
echo "2. Visit http://localhost:5173"
echo "3. Sign Up as STUDENT 1"
echo "   - Email: student1@demo.com"
echo "   - Password: Demo123456"
echo "   - Click 'Create Account'"
echo ""
echo "Press Enter when Student 1 is signed up..."
read

# PART 5: STUDENT ENROLLMENT
echo ""
echo "📝 PART 5: ENROLL IN COURSE (15 seconds)"
echo "=========================================="
echo "Student 1 Dashboard:"
echo "1. Click '+ Enroll Course'"
echo "2. Enter any code (e.g., 'QMECH123')"
echo "3. Click 'Enroll'"
echo "4. You should see 'Quantum Mechanics' course"
echo "5. Expand course and see 'Wave Functions Fundamentals' lecture"
echo "6. Click 'Give Feedback'"
echo ""
echo "Press Enter when on Student Feedback page..."
read

# PART 6: SUBMIT FEEDBACK
echo ""
echo "✨ PART 6: SUBMIT FEEDBACK (20 seconds)"
echo "========================================="
echo "1. Click the 🟡 YELLOW button (⚠️ Partially Understood)"
echo "2. Check boxes:"
echo "   ☑ Wave Function"
echo "   ☑ Schrodinger Equation"
echo "3. Select reason: 'Mathematical notation too complex'"
echo "4. Click 'Submit Feedback'"
echo "5. Watch for CONFETTI animation! 🎉"
echo "6. Get redirected to Student Dashboard"
echo ""
echo "Press Enter after confetti animation..."
read

# PART 7: LIVE HEATMAP
echo ""
echo "📊 PART 7: VIEW LIVE HEATMAP (20 seconds)"
echo "=========================================="
echo "1. Switch back to PROFESSOR window"
echo "2. Reload the page or just look at right panel"
echo "3. You should see:"
echo "   ✅ Fully Understood: 0/1 (0%)"
echo "   ⚠️  Partially Understood: 1/1 (100%)"
echo "   ❌ Need Clarity: 0/1 (0%)"
echo ""
echo "4. See Difficult Topics section showing:"
echo "   - Wave Function"
echo "   - Schrodinger Equation"
echo ""
echo "5. Yellow bar should be FULL (100%)"
echo ""
echo "Press Enter when you see the heatmap..."
read

# PART 8: MORE STUDENTS
echo ""
echo "👨‍🎓 PART 8: ADD MORE STUDENT FEEDBACK (30 seconds)"
echo "=================================================="
echo "1. Open ANOTHER INCOGNITO window"
echo "2. Sign up Student 2:"
echo "   - Email: student2@demo.com"
echo "   - Password: Demo123456"
echo "3. Enroll in course"
echo "4. Give Feedback:"
echo "   - Click 🔴 RED button (❌ Need Clarity)"
echo "   - Check: 'Probability Density'"
echo "5. Submit (CONFETTI again!)"
echo ""
echo "Press Enter when Student 2 submits..."
read

# PART 9: WATCH HEATMAP UPDATE
echo ""
echo "🔄 PART 9: WATCH HEATMAP CHANGE (20 seconds)"
echo "=============================================="
echo "1. Back in PROFESSOR window"
echo "2. WATCH THE HEATMAP UPDATE LIVE (no refresh needed!)"
echo ""
echo "You should now see:"
echo "   ✅ Fully Understood: 0/2 (0%)"
echo "   ⚠️  Partially Understood: 1/2 (50%)"
echo "   ❌ Need Clarity: 1/2 (50%)"
echo ""
echo "3. Colors change:"
echo "   - Yellow bar is 50%"
echo "   - Red bar is 50%"
echo "4. Difficult topics show all selected topics"
echo ""
echo "Press Enter when you see the update..."
read

# PART 10: MOBILE TEST
echo ""
echo "📱 PART 10: MOBILE TEST (30 seconds - OPTIONAL)"
echo "==============================================="
echo "1. Open phone/tablet to: http://YOUR_MACHINE_IP:5173"
echo "   (Find IP: ipconfig on Windows, ifconfig on Mac)"
echo "2. Sign up as Student 3"
echo "3. Enroll and give feedback on mobile"
echo "4. Watch professor heatmap update LIVE!"
echo ""
echo "Press Enter to continue..."
read

# FINAL SUMMARY
echo ""
echo "🎉 DEMO COMPLETE!"
echo "=================="
echo ""
echo "✅ What You Just Saw:"
echo "   1. Professor creates course & lecture (2 min)"
echo "   2. Students enroll via code"
echo "   3. Students submit feedback in 10 seconds"
echo "   4. Professor sees LIVE heatmap update"
echo "   5. Colors show comprehension (Green/Yellow/Red)"
echo "   6. Mobile responsive"
echo ""
echo "📊 Key Metrics:"
echo "   - Course creation: 1 minute"
echo "   - Lecture creation: 2 minutes"
echo "   - Student feedback: 10 seconds"
echo "   - Heatmap update: <100ms (Realtime)"
echo ""
echo "🚀 Next Steps:"
echo "   - Deploy to Vercel for live demo"
echo "   - Add more students (50+ supported)"
echo "   - Enable AI insights with OpenAI"
echo "   - Generate revision plans PDF"
echo ""
echo "💡 Judge Talking Points:"
echo "   - Real-time feedback (WebSocket)"
echo "   - Instant heatmap updates"
echo "   - 100% mobile responsive"
echo "   - Secure RLS policies"
echo "   - Production-ready MVP"
echo ""
echo "Good luck with your demo! 🎓✨"
